# config.yaml
cifar10_resnet18:
  checkpoint_file: checkpoints/event_resnet18_cifar10withids_seed0.pt
  dataset: cifar10withids
  model: resnet18
  augment: false
  val_frac: 0
  data_dir: /data/image_data/cifar10/

  seed: 0
  lr: 0.001 
  batch_size: 128
  optimizer: sgd
  weight_decay: 0.0005
  epochs: 500
  momentum: 0.9
  lr_decay_rate: 0.1
  lr_decay_epochs: "15, 20, 25"

  weights_init: random 
  num_workers: 4
